# Generated by Django 3.1.4 on 2025-07-01 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=44, verbose_name='Nome')),
            ],
            options={
                'db_table': 'tb_cidade',
            },
        ),
        migrations.CreateModel(
            name='ConfigEtl',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(verbose_name='Ativo')),
                ('data_atualizacao_inicial', models.DateField(blank=True, null=True, verbose_name='Data Inicial')),
            ],
            options={
                'db_table': 'tb_config_etl',
            },
        ),
        migrations.CreateModel(
            name='Estacao',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_estacao', models.BigIntegerField(verbose_name='Código da Estação')),
                ('codigo_bacia', models.BigIntegerField(blank=True, null=True, verbose_name='Código da Bacia')),
                ('codigo_sub_bacia', models.BigIntegerField(blank=True, null=True, verbose_name='Código da Sub-Bacia')),
                ('nome', models.CharField(blank=True, max_length=144, null=True, verbose_name='Nome')),
                ('latitude', models.CharField(blank=True, max_length=44, null=True, verbose_name='Latitude')),
                ('longitude', models.CharField(blank=True, max_length=44, null=True, verbose_name='Longitude')),
                ('altitude', models.CharField(blank=True, max_length=44, null=True, verbose_name='Altitude')),
                ('operando', models.IntegerField(blank=True, null=True, verbose_name='Operando')),
                ('ultima_atualizacao', models.DateTimeField(blank=True, null=True, verbose_name='Última Atualização')),
                ('cidade', models.ForeignKey(db_column='co_cidade', on_delete=django.db.models.deletion.CASCADE, related_name='estacoes', to='core.cidade', verbose_name='Cidade')),
            ],
            options={
                'db_table': 'tb_estacao',
            },
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=44, verbose_name='Nome')),
            ],
            options={
                'db_table': 'tb_estado',
            },
        ),
        migrations.CreateModel(
            name='ReportEtl',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateTimeField(verbose_name='Início ETL')),
                ('data_fim', models.DateTimeField(verbose_name='Fim ETL')),
                ('erro', models.CharField(blank=True, max_length=128, null=True, verbose_name='Erro')),
            ],
            options={
                'db_table': 'tb_report_etl',
            },
        ),
        migrations.CreateModel(
            name='ResumoMensal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicial', models.DateTimeField(blank=True, null=True, verbose_name='Data Inicial')),
                ('data_insercao_ana', models.DateTimeField(blank=True, null=True, verbose_name='Data Inserção ANA')),
                ('metodo_obtencao', models.IntegerField(blank=True, null=True, verbose_name='Método de Obtenção')),
                ('nivel_consistencia', models.IntegerField(blank=True, null=True, verbose_name='Nível de Consistência')),
                ('vazao_media', models.FloatField(blank=True, null=True, verbose_name='Vazão Média')),
                ('vazao_maxima', models.FloatField(blank=True, null=True, verbose_name='Vazão Máxima')),
                ('vazao_minima', models.FloatField(blank=True, null=True, verbose_name='Vazão Mínima')),
                ('vazao_media_real', models.FloatField(blank=True, null=True, verbose_name='Vazão Média Real')),
                ('vazao_maxima_real', models.FloatField(blank=True, null=True, verbose_name='Vazão Máxima Real')),
                ('vazao_minima_real', models.FloatField(blank=True, null=True, verbose_name='Vazão Mínima Real')),
                ('estacao', models.ForeignKey(db_column='co_estacao', on_delete=django.db.models.deletion.CASCADE, related_name='resumos_mensal', to='core.estacao', verbose_name='Estação')),
            ],
            options={
                'db_table': 'tb_resumo_mensal',
            },
        ),
        migrations.CreateModel(
            name='Rio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=144, verbose_name='Nome')),
                ('descricao', models.CharField(blank=True, max_length=88, null=True, verbose_name='Descrição')),
            ],
            options={
                'db_table': 'tb_rio',
            },
        ),
        migrations.CreateModel(
            name='VazaoDiaria',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('vazao', models.FloatField(blank=True, null=True, verbose_name='Vazão')),
                ('vazao_status', models.IntegerField(blank=True, null=True, verbose_name='Status da Vazão')),
                ('data_vazao', models.DateField(verbose_name='Data da Vazão')),
                ('resumo_mensal', models.ForeignKey(db_column='co_resumo_mensal', on_delete=django.db.models.deletion.CASCADE, related_name='vazoes_diarias', to='core.resumomensal', verbose_name='Resumo Mensal')),
            ],
            options={
                'db_table': 'tb_vazao_diaria',
            },
        ),
        migrations.AddField(
            model_name='estacao',
            name='rio',
            field=models.ForeignKey(db_column='co_rio', on_delete=django.db.models.deletion.CASCADE, related_name='estacoes', to='core.rio', verbose_name='Rio'),
        ),
        migrations.AddField(
            model_name='cidade',
            name='estado',
            field=models.ForeignKey(db_column='co_estado', on_delete=django.db.models.deletion.CASCADE, related_name='cidades', to='core.estado', verbose_name='Estado'),
        ),
        migrations.CreateModel(
            name='RioCidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cidade', models.ForeignKey(db_column='co_cidade', on_delete=django.db.models.deletion.CASCADE, related_name='rios_cidade', to='core.cidade', verbose_name='Cidade')),
                ('rio', models.ForeignKey(db_column='co_rio', on_delete=django.db.models.deletion.CASCADE, related_name='rios_cidade', to='core.rio', verbose_name='Rio')),
            ],
            options={
                'db_table': 'tb_rio_cidade',
                'unique_together': {('rio', 'cidade')},
            },
        ),
    ]
